version: "3.8"

services:
  postgres:
    image: postgres:<postgres image version>
    container_name: local-postgres
    restart: always
    environment:
      POSTGRES_DB: <your_db>
      POSTGRES_USER: <your_username>
      POSTGRES_PASSWORD: <your_password>
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

volumes:
  postgres_data:
    driver: local

networks:
  backend_network:
    driver: bridge
